// Compile-only check: every public header parses standalone and together.
#include "sovsolve/core/AlignedAllocator.hpp"
#include "sovsolve/core/DenseMatrix.hpp"
#include "sovsolve/core/LinearOperator.hpp"
#include "sovsolve/core/NameArena.hpp"
#include "sovsolve/core/SparseMatrix.hpp"
#include "sovsolve/core/Span.hpp"
#include "sovsolve/core/Status.hpp"
#include "sovsolve/core/Types.hpp"
#include "sovsolve/core/Vector.hpp"
#include "sovsolve/core/Workspace.hpp"
#include "sovsolve/model/Canonical.hpp"
#include "sovsolve/model/Options.hpp"
#include "sovsolve/model/Problem.hpp"
#include "sovsolve/model/Solution.hpp"
#include "sovsolve/model/Transform.hpp"
#include "sovsolve/analysis/MatrixAnalysis.hpp"
#include "sovsolve/io/Load.hpp"
#include "sovsolve/solver/ConvergenceChecker.hpp"
#include "sovsolve/solver/Diagnostics.hpp"
#include "sovsolve/solver/DualBound.hpp"
#include "sovsolve/solver/Initializer.hpp"
#include "sovsolve/solver/KktSystem.hpp"
#include "sovsolve/solver/Logging.hpp"
#include "sovsolve/solver/Homogeneous.hpp"
#include "sovsolve/solver/HostKkt.hpp"
#include "sovsolve/solver/HomogeneousNewton.hpp"
#include "sovsolve/solver/HomogeneousSolve.hpp"
#include "sovsolve/solver/HomogeneousStep.hpp"
#include "sovsolve/solver/Iis.hpp"
#include "sovsolve/solver/LpSolve.hpp"
#include "sovsolve/solver/Regularization.hpp"
#include "sovsolve/solver/Residuals.hpp"
#include "sovsolve/solver/Scaler.hpp"
#include "sovsolve/solver/SolutionQuality.hpp"
#include "sovsolve/solver/SolutionReconstructor.hpp"
#include "sovsolve/solver/SolverState.hpp"
// Module 23 (simplex) and Module 24 (PDLP). Host-only, but the point of this
// check is that each header stands alone -- one that only compiles because
// some other header happened to be included first is a latent break for the
// next file that includes it in a different order.
#include "sovsolve/solver/simplex/Basis.hpp"
#include "sovsolve/solver/simplex/DualSimplex.hpp"
#include "sovsolve/solver/simplex/LuFactor.hpp"
#include "sovsolve/solver/simplex/PrimalSimplex.hpp"
#include "sovsolve/solver/simplex/SimplexResult.hpp"
#include "sovsolve/solver/simplex/SimplexSolution.hpp"
#include "sovsolve/solver/simplex/SolveSimplex.hpp"
#include "sovsolve/solver/pdlp/DualityGap.hpp"
#include "sovsolve/solver/pdlp/Infeasibility.hpp"
#include "sovsolve/solver/pdlp/IterationBackend.hpp"
#include "sovsolve/solver/pdlp/MatVec.hpp"
#include "sovsolve/solver/pdlp/Pdlp.hpp"
#include "sovsolve/solver/pdlp/PdlpSolution.hpp"
#include "sovsolve/solver/pdlp/TrustRegion.hpp"
// GPU-boundary headers: plain C++ declarations (no CUDA-specific syntax), so
// they compile under any C++ compiler even though their .cu bodies only
// build under SOVSOLVE_ENABLE_CUDA.
#include "sovsolve/solver/gpu/KktBuilder.hpp"
#include "sovsolve/solver/gpu/LinearSolver.hpp"
#include "sovsolve/solver/gpu/MuController.hpp"
#include "sovsolve/solver/gpu/NewtonRecovery.hpp"
#include "sovsolve/solver/gpu/Ordering.hpp"
#include "sovsolve/solver/gpu/PdlpDevice.hpp"
#include "sovsolve/solver/gpu/PdlpMatVec.hpp"
#include "sovsolve/solver/gpu/PredictorCorrector.hpp"
#include "sovsolve/solver/gpu/ResidualCalculator.hpp"
#include "sovsolve/solver/gpu/Solve.hpp"
#include "sovsolve/solver/gpu/StateUpdate.hpp"
#include "sovsolve/solver/gpu/StepLength.hpp"

int main() { return 0; }
